version: '3.9'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - language-x-change-api

  language-x-change-api:
    build:
      context: ./
      dockerfile: ./Dockerfile_m1

    restart: always

    volumes:
      - './:/app'
      - '/app/upload'

    ports:
      - '8000'

    environment:
      HUGGING_FACE_HUB_TOKEN: <ENTER THE HUGGING FACE API KEY>

    command: >
      sh -c "pip install -r requirements_m1.txt && uvicorn main:app --reload --host 0.0.0.0"

networks:
  default:
    driver: bridge
    name: language-x-change
