version: '3.8'

services:
  # mongo:
  #     image: mongo:latest
  #     ports:
  #       - "27017:27017"
      
  #     volumes:
        
  #     restart: always

  api:
    build:
      context: ./
      dockerfile: ./Dockerfile

    restart: always

    volumes:
      - "./:/app"
      - "../whisper/training/model:/app/model"

    ports:
      - "8000:8000"

    command: >
      sh -c "uvicorn main:app --reload --host 0.0.0.0"